//PACKAGE ENGINE.COMMAND;
//
//IMPORT JAVA.SECURITY.INVALIDPARAMETEREXCEPTION;
//IMPORT JAVA.UTIL.ARRAYLIST;
//
//IMPORT COMMANDS.RELOCATECOMMAND;
//IMPORT COMMANDS.SEQUENCECOMMAND;
//
//IMPORT BRIDGE.TRANSFERABLE.INTERFACES.COMMANDINTERFACE;
//IMPORT BRIDGE.TRANSFERABLE.PROXY.ENTITYVIEWPROXY;
//IMPORT BRIDGE.TRANSFERABLE.PROXY.SESSIONPROXY;
//
//PUBLIC CLASS ALIGNENTITIESCOMMAND IMPLEMENTS COMMANDINTERFACE {
//	PUBLIC STATIC INT ALIGN_NONE = 0;
//	PUBLIC STATIC INT ALIGN_TOP = 1;
//	PUBLIC STATIC INT ALIGN_BOT = 2;
//	PUBLIC STATIC INT ALIGN_LEFT = 3;
//	PUBLIC STATIC INT ALIGN_RIGHT = 4;
//	PUBLIC STATIC INT ALIGN_VERTICAL_CENTER=5;
//	PUBLIC STATIC INT ALIGN_HORIZONTAL_CENTER=6;
//
//	PRIVATE INT FLAG1;
//	PRIVATE INT FLAG2;
//	PRIVATE SESSIONPROXY SESSION;
//	PRIVATE COMMANDINTERFACE SEQCMD;
//
//	/*
//	 * THE FLAGS ARE STATICS OF THIS CLASS , CONCURRENT FLAGS CAN NOT BE USED
//	 * (YOU CAN'T ALIGN BOTH TOP AND BOTTOM IN THE SAME COMMAND)
//	 */
//	PUBLIC ALIGNENTITIESCOMMAND(INT FLAG1, INT FLAG2, SESSIONPROXY SESSION) {
//		THIS.FLAG1 = FLAG1;
//		THIS.FLAG2 = FLAG2;
//		THIS.SESSION = SESSION;
//		SEQCMD = NULL;
//	}
//
//	PUBLIC ALIGNENTITIESCOMMAND(INT FLAG1, SESSIONPROXY SESSION) {
//		THIS.FLAG1 = FLAG1;
//		THIS.SESSION = SESSION;
//		SEQCMD = NULL;
//	}
//
//	@OVERRIDE
//	PUBLIC BOOLEAN EXECUTE() THROWS INVALIDPARAMETEREXCEPTION {
//		INT MINX = INTEGER.MAX_VALUE;
//		INT MINY = INTEGER.MAX_VALUE;
//		INT MAXX = -1;
//		INT MAXY = -1;
//
//		IF (SESSION.GETSELECTEDENTITIES().SIZE() < 2)
//			RETURN FALSE;
//
//		ENTITYVIEWPROXY PIVOTTOP = NULL;
//		ENTITYVIEWPROXY PIVOTBOT = NULL;
//		ENTITYVIEWPROXY PIVOTLEFT = NULL;
//		ENTITYVIEWPROXY PIVOTRIGHT = NULL;
//		FOR (ENTITYVIEWPROXY EV : SESSION.GETSELECTEDENTITIES()) {
//			IF (EV.GETMODEL().GETLOCATION().X < MINX) {//RIGHT
//				MINX = EV.GETMODEL().GETLOCATION().X;
//				PIVOTRIGHT = EV;
//			}
//			IF (EV.GETMODEL().GETLOCATION().Y < MINY) {//ALIGN TOP
//				MINY = EV.GETMODEL().GETLOCATION().Y;
//				PIVOTTOP = EV;
//			}
//			IF (EV.GETMODEL().GETLOCATION().X > MAXX) { //LEFT
//				MAXX = EV.GETMODEL().GETLOCATION().X;
//				PIVOTLEFT = EV;
//			}
//			IF (EV.GETMODEL().GETLOCATION().Y > MAXY) {//ALIGN BOT
//				MAXY = EV.GETMODEL().GETLOCATION().Y;
//				PIVOTBOT = EV;
//			}
//		}
//		
//		
//		INT VERTICALCENTER = (MAXX-PIVOTLEFT.GETWIDTH()/2-MINX)/2;
//		INT HORIZONTALCENTER = (MAXY-PIVOTBOT.GETHEIGHT()/2-MINY)/2;
//
//		ARRAYLIST<COMMANDINTERFACE> CMDS = NEW ARRAYLIST<COMMANDINTERFACE>();
//		FOR (ENTITYVIEWPROXY EV : SESSION.GETSELECTEDENTITIES()) {
//			IF ((FLAG1 == ALIGN_VERTICAL_CENTER || FLAG2 == ALIGN_VERTICAL_CENTER))
//				CMDS.ADD(NEW RELOCATECOMMAND(EV, VERTICALCENTER-EV.GETX()-EV.GETWIDTH()/2, 0));
//			ELSE IF ((FLAG1 == ALIGN_HORIZONTAL_CENTER || FLAG2 == ALIGN_HORIZONTAL_CENTER))
//				CMDS.ADD(NEW RELOCATECOMMAND(EV, 0, HORIZONTALCENTER-EV.GETY()-EV.GETHEIGHT()/2));
//			IF ((FLAG1 == ALIGN_TOP || FLAG2 == ALIGN_TOP) && !EV.EQUALS(PIVOTTOP))
//				CMDS.ADD(NEW RELOCATECOMMAND(EV, 0, MINY - EV.GETMODEL().GETLOCATION().Y));
//			ELSE IF ((FLAG1 == ALIGN_BOT || FLAG2 == ALIGN_BOT) && !EV.EQUALS(PIVOTBOT))
//				CMDS.ADD(NEW RELOCATECOMMAND(EV, 0, MAXY - EV.GETMODEL().GETLOCATION().Y));
//			IF ((FLAG1 == ALIGN_LEFT || FLAG2 == ALIGN_LEFT) && !EV.EQUALS(PIVOTLEFT))
//				CMDS.ADD(NEW RELOCATECOMMAND(EV, MAXX - EV.GETMODEL().GETLOCATION().X, 0));
//			ELSE IF ((FLAG1 == ALIGN_RIGHT || FLAG2 == ALIGN_RIGHT) && !EV.EQUALS(PIVOTRIGHT))
//				CMDS.ADD(NEW RELOCATECOMMAND(EV, MINX - EV.GETMODEL().GETLOCATION().X, 0));
//		}
//		SEQCMD = NEW SEQUENCECOMMAND(CMDS);
//		
//		BOOLEAN RET = !CMDS.ISEMPTY() && SEQCMD.EXECUTE();
//		IF (!RET)
//			SESSION.POSTERRORMESSAGE("CAN NOT RELOCATE THERE , NEGATIVE COORDONATES OR TOO SMALL CANVAS");
//		SESSION.REPAINTSELECTEDSHEET();
//		RETURN RET;
//	}
//
//	@OVERRIDE
//	PUBLIC VOID UNDO() {
//		IF (ISVALID())
//			SEQCMD.UNDO();
//	}
//
//	@OVERRIDE
//	PUBLIC BOOLEAN ISVALID() {
//		RETURN SEQCMD != NULL;
//	}
//
// }
